### ISSUE TITLE
Plugin requires boto3 module but is already installed

### ISSUE THREAD

**Issue by marcusmyers** [clburlison/Munki-s3Repo-Plugin#14]
I'm just getting started with this plugin and followed the steps for setup but every time I run `munkiimport --configure` I get the following error:

```bash
This plugin uses the boto3 module. Please install it with:
   pip install boto3 --user
```

Is there something else I'm missing that's not documented?

**Comment by rickheil** [comment]
Python is unable to find the boto3 module. If you are running munkiimport as your own user, the pip command that spits back should install it for you. If you are running it as another user, you should install boto3 as that user with pip.

**Comment by clburlison** [comment]
In the title for this issue, you say boto3 is already installed. I am going to bet it is installed in a path outside of your python sys.path or maybe you have it installed for python3?

When munki runs it is using the stock python that Apple ships, `/usr/bin/python` and for the context of this plugin it will run as the your console user.

Can you give me the output of?

```bash
/usr/bin/python -c 'import sys; print(sys.path); import boto3; print(boto3.__version__)'
```

For reference purposes on my machine I get:

```bash
['', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/clburlison/Library/Python/2.7/lib/python/site-packages', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']
1.7.14
```

**Comment by marcusmyers** [comment]
Good to know! Here's my output:

```bash
/usr/bin/python -c 'import sys; print(sys.path); import boto3; print(boto3.__version__)'
['', '/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/mmyers/Library/Python/2.7/lib/python/site-packages', '/Library/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mmyers/Library/Python/2.7/lib/python/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/Users/mmyers/Library/Python/2.7/lib/python/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Users/mmyers/Library/Python/2.7/lib/python/site-packages/botocore/session.py", line 27, in <module>
    import botocore.client
  File "/Users/mmyers/Library/Python/2.7/lib/python/site-packages/botocore/client.py", line 16, in <module>
    from botocore import waiter, xform_name
  File "/Users/mmyers/Library/Python/2.7/lib/python/site-packages/botocore/waiter.py", line 13, in <module>
    import jmespath
ImportError: No module named jmespath
```

I do have python installed via homebrew as well and it obviously is that path for my user. Is there something I can change like an environment variable? Maybe PYTHONPATH or something?

**Comment by marcusmyers** [comment]
I figured out my issue and here's the steps I ran to fix it.

1. `brew unlink python@2`
2. Opened a new terminal and followed the [Setup](https://github.com/clburlison/Munki-s3Repo-Plugin#setup) instructions.

I'm going to close this issue.

**Comment by SachinParmar** [comment]
I managed to get this working by:

1. Removing munki tools, re-installing it
2. Removing pip and homebrew, re-installing it 
3. Re-ran `pip install boto3 --user`
4. Then `munkiimport --configure` worked as expected
